### ISSUE TITLE
Bug clicknupload.org

### ISSUE THREAD

**Issue by alvahn** [hell-sh/Universal-Bypass#64]
Example link : https://clicknupload.org/9a0iobhuuw2q

**Comment by timmyrs** [comment]
I see nothing wrong.

**Comment by alvahn** [comment]
@timmyrs make site broken 
https://image.prntscr.com/image/Sl3jfNMOQC2S57eoR5vONg.png

**Comment by timmyrs** [comment]
I don't think that's an issue caused by Universal Bypass.

**Comment by alvahn** [comment]
@timmyrs ahh sorry because another userscript
