### ISSUE TITLE
Add bypass for telolet.in

### ISSUE THREAD

**Issue by anakaiti** [hell-sh/Universal-Bypass#76]
Scope: telolet.in

Sample links: [1](http://telolet.in//?go=aHR0cDovL3ZpdmFkcy5uZXQva0NYcm8=) [2](http://telolet.in//?go=aHR0cDovL3ZpdmFkcy5uZXQvbFNaMA==)

Code:  

    document.location.href = atob(document.location.search.split('go=')[1])

Resolved links are usually also ad link shorteners.

**Comment by timmyrs** [comment]
Thanks for the suggestion. I've added a bypass for telolet.in in Universal Bypass 5.6.4.
