### ISSUE TITLE
[Request] www.spaste.com

### ISSUE THREAD

**Issue by Nodens-** [hell-sh/Universal-Bypass#78]
This one hides a url under a captcha and also has a 3sec timer after solving the captcha.
Example: http://www.spaste.com/go/CDcnaY

**Comment by timmyrs** [comment]
As you've already mentioned, they have a captcha and there also is backend validation to make sure you actually passed the captcha and waited those 3 seconds so not much I can do to bypass that.

**Comment by Nodens-** [comment]
Understandable about the captcha. The timer is not bypassable either?
